spring.application.name=shopping-backend

spring.datasource.url=jdbc:postgresql://localhost:54943/ScrapeDb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=ADMIN

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.web.cors.allowed-origins="*"
spring.web.cors.allowed-methods="*"
spring.web.cors.allowed-headers="*"

spring.management.endpoints.web.exposure.include=health,info,metrics
spring.management.endpoint.health.show-details=always

server.port=8080
scraper.python.url=http://localhost:8001

spring.docker.compose.enabled=false